server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: servidor-gateway
  cloud: 
    gateway:      
      routes:
      - id: serv-productos        
        uri: lb://servicio-productos1 #http://localhost:8080
        predicates:
          - Path=/sproductos/**
        filters:
          - RewritePath=/sproductos/*, /

